/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "EdmundCode.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_handleEdmundBehaviour_TestNoFalseExitsFromStateShutdown(void);
extern void test_handleEdmundBehaviour_TestTrueExitsFromIdleState(void);
extern void test_handleEdmundBehaviour_TestNoFalseExitsFromStatePoweringUp(void);
extern void test_handleEdmundBehaviour_TestTrueExitsFromStatePoweringUp_behaviourEventButtonDownLT1000(void);
extern void test_handleEdmundBehaviour_TestTrueExitsFromStatePoweringUp_behaviourEventButtonDownGT1000LT5000(void);
extern void test_handleEdmundBehaviour_TestTrueExitsFromStatePoweringUp_behaviourEventButtonDownGT5000(void);
extern void test_handleEdmundBehaviour_TestNoFalseExitsFrombehaviourStatePoweringDn(void);
extern void test_handleEdmundBehaviour_TestTrueExitsFrombehaviourStatePoweringDn_behaviourEventLowBattery(void);
extern void test_handleEdmundBehaviour_TestTrueExitsFrombehaviourStatePoweringDn_behaviourEventButtonDownGT2000Rleased(void);
extern void test_handleEdmundBehaviour_TestNoFalseExitsFrombehaviourStatePoweringUpLowBattery(void);
extern void test_handleEdmundBehaviour_TestTrue1ExitsFrombehaviourStatePoweringUpLowBattery_behaviourEventButtonDownLT1000(void);
extern void test_handleEdmundBehaviour_TestTrue1ExitsFrombehaviourStatePoweringUpLowBattery_behaviourEventButtonDownGT1000LT5000(void);
extern void test_handleEdmundBehaviour_TestTrue1ExitsFrombehaviourStatePoweringUpLowBattery_behaviourEventButtonDownGT5000(void);
extern void test_handleEdmundBehaviour_TestNoFalseExitsFrombehaviourStateConnectedAuthApp(void);
extern void test_handleEdmundBehaviour_TestTrueExitsFrombehaviourStateConnectedAuthApp(void);
extern void test_handleEdmundBehaviour_TestNoFalseExitsFromStateAdvertising(void);
extern void test_handleEdmundBehaviour_TestTrueExitsFromStateAdvertising_behaviourEventConnectedAuth(void);
extern void test_handleEdmundBehaviour_TestTrueExitsFromStateAdvertising_behaviourEventButtonDownGT50(void);
extern void test_handleEdmundBehaviour_TestNoFalseExitsFromConnectedUnAuthApp(void);
extern void test_handleEdmundBehaviour_TestTrueExitsFromConnectedUnAuthApp(void);
extern void test_handleEdmundBehaviour_TestNoFalseExitsFrombehaviourStateLowBattShutdown(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test/TestEdmundCode.c");
  run_test(test_handleEdmundBehaviour_TestNoFalseExitsFromStateShutdown, "test_handleEdmundBehaviour_TestNoFalseExitsFromStateShutdown", 19);
  run_test(test_handleEdmundBehaviour_TestTrueExitsFromIdleState, "test_handleEdmundBehaviour_TestTrueExitsFromIdleState", 35);
  run_test(test_handleEdmundBehaviour_TestNoFalseExitsFromStatePoweringUp, "test_handleEdmundBehaviour_TestNoFalseExitsFromStatePoweringUp", 46);
  run_test(test_handleEdmundBehaviour_TestTrueExitsFromStatePoweringUp_behaviourEventButtonDownLT1000, "test_handleEdmundBehaviour_TestTrueExitsFromStatePoweringUp_behaviourEventButtonDownLT1000", 60);
  run_test(test_handleEdmundBehaviour_TestTrueExitsFromStatePoweringUp_behaviourEventButtonDownGT1000LT5000, "test_handleEdmundBehaviour_TestTrueExitsFromStatePoweringUp_behaviourEventButtonDownGT1000LT5000", 66);
  run_test(test_handleEdmundBehaviour_TestTrueExitsFromStatePoweringUp_behaviourEventButtonDownGT5000, "test_handleEdmundBehaviour_TestTrueExitsFromStatePoweringUp_behaviourEventButtonDownGT5000", 72);
  run_test(test_handleEdmundBehaviour_TestNoFalseExitsFrombehaviourStatePoweringDn, "test_handleEdmundBehaviour_TestNoFalseExitsFrombehaviourStatePoweringDn", 82);
  run_test(test_handleEdmundBehaviour_TestTrueExitsFrombehaviourStatePoweringDn_behaviourEventLowBattery, "test_handleEdmundBehaviour_TestTrueExitsFrombehaviourStatePoweringDn_behaviourEventLowBattery", 97);
  run_test(test_handleEdmundBehaviour_TestTrueExitsFrombehaviourStatePoweringDn_behaviourEventButtonDownGT2000Rleased, "test_handleEdmundBehaviour_TestTrueExitsFrombehaviourStatePoweringDn_behaviourEventButtonDownGT2000Rleased", 103);
  run_test(test_handleEdmundBehaviour_TestNoFalseExitsFrombehaviourStatePoweringUpLowBattery, "test_handleEdmundBehaviour_TestNoFalseExitsFrombehaviourStatePoweringUpLowBattery", 114);
  run_test(test_handleEdmundBehaviour_TestTrue1ExitsFrombehaviourStatePoweringUpLowBattery_behaviourEventButtonDownLT1000, "test_handleEdmundBehaviour_TestTrue1ExitsFrombehaviourStatePoweringUpLowBattery_behaviourEventButtonDownLT1000", 128);
  run_test(test_handleEdmundBehaviour_TestTrue1ExitsFrombehaviourStatePoweringUpLowBattery_behaviourEventButtonDownGT1000LT5000, "test_handleEdmundBehaviour_TestTrue1ExitsFrombehaviourStatePoweringUpLowBattery_behaviourEventButtonDownGT1000LT5000", 134);
  run_test(test_handleEdmundBehaviour_TestTrue1ExitsFrombehaviourStatePoweringUpLowBattery_behaviourEventButtonDownGT5000, "test_handleEdmundBehaviour_TestTrue1ExitsFrombehaviourStatePoweringUpLowBattery_behaviourEventButtonDownGT5000", 140);
  run_test(test_handleEdmundBehaviour_TestNoFalseExitsFrombehaviourStateConnectedAuthApp, "test_handleEdmundBehaviour_TestNoFalseExitsFrombehaviourStateConnectedAuthApp", 150);
  run_test(test_handleEdmundBehaviour_TestTrueExitsFrombehaviourStateConnectedAuthApp, "test_handleEdmundBehaviour_TestTrueExitsFrombehaviourStateConnectedAuthApp", 166);
  run_test(test_handleEdmundBehaviour_TestNoFalseExitsFromStateAdvertising, "test_handleEdmundBehaviour_TestNoFalseExitsFromStateAdvertising", 175);
  run_test(test_handleEdmundBehaviour_TestTrueExitsFromStateAdvertising_behaviourEventConnectedAuth, "test_handleEdmundBehaviour_TestTrueExitsFromStateAdvertising_behaviourEventConnectedAuth", 190);
  run_test(test_handleEdmundBehaviour_TestTrueExitsFromStateAdvertising_behaviourEventButtonDownGT50, "test_handleEdmundBehaviour_TestTrueExitsFromStateAdvertising_behaviourEventButtonDownGT50", 196);
  run_test(test_handleEdmundBehaviour_TestNoFalseExitsFromConnectedUnAuthApp, "test_handleEdmundBehaviour_TestNoFalseExitsFromConnectedUnAuthApp", 206);
  run_test(test_handleEdmundBehaviour_TestTrueExitsFromConnectedUnAuthApp, "test_handleEdmundBehaviour_TestTrueExitsFromConnectedUnAuthApp", 222);
  run_test(test_handleEdmundBehaviour_TestNoFalseExitsFrombehaviourStateLowBattShutdown, "test_handleEdmundBehaviour_TestNoFalseExitsFrombehaviourStateLowBattShutdown", 232);

  return UnityEnd();
}
